#!/usr/bin/env bash
# distro_config/setup_env.sh
# Shell environment setup, run by `make run` (see Makefile's `setup_env` target):
#   1. Prompts to create the project .env from .env.example (the single AUTHORED
#      source of truth — Context7/Tavily/DeepSeek/CodeRabbit keys).
#   2. Generates ~/.claude/.env FROM the project .env — a copy, never a second
#      authored file, so the two cannot drift. It keeps its own path so the
#      shell still works if this repo moves or is deleted.
#   3. Bootstraps ~/.bashrc to source ~/.claude/.env, exporting every key it
#      finds into every new shell.
#   Both .env files are written mode 600 — they hold credentials.
#      See the "Machine Secrets" section in README.md for the full key reference.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${REPO_ROOT}/lib/common.sh"

ENV_EXAMPLE="${REPO_ROOT}/.env.example"
ENV_FILE="${REPO_ROOT}/.env"
CLAUDE_DIR="${HOME}/.claude"
CLAUDE_ENV_FILE="${CLAUDE_DIR}/.env"
BASHRC="${HOME}/.bashrc"
CLAUDE_ENV_MARKER="# Claude Code per-machine secrets — see README.md 'Machine Secrets'"

prompt_create_project_env() {
    if [[ -f "${ENV_FILE}" ]]; then
        print_status "success" ".env already exists — skipping."
        return 0
    fi

    if [[ ! -f "${ENV_EXAMPLE}" ]]; then
        print_status "warning" "No .env.example found — skipping env setup."
        return 0
    fi

    local answer

    echo ""
    echo "┌─────────────────────────────────────────────────────────────┐"
    echo "│  .env file not found                                        │"
    echo "│                                                             │"
    echo "│  Some tools (Context7, Tavily) require API keys stored      │"
    echo "│  in a .env file. Without it:                                │"
    echo "│    • Context7 MCP server won't authenticate                 │"
    echo "│    • Tavily search/research tools will be unavailable       │"
    echo "│    • Any script sourcing .env will silently skip those keys │"
    echo "└─────────────────────────────────────────────────────────────┘"
    echo ""
    read -r -p "  Create .env from .env.example now? [Y/n] " answer

    case "${answer}" in
        [nN]*)
            print_status "info" "Skipped. Create it later with: cp .env.example .env"
            ;;
        *)
            cp "${ENV_EXAMPLE}" "${ENV_FILE}"
            chmod 600 "${ENV_FILE}"
            print_status "success" ".env created. Open it and replace placeholder values: \$EDITOR ${ENV_FILE}"
            ;;
    esac
}

# Generates ~/.claude/.env FROM the project .env — the project .env is the
# single authored source of truth (documented by .env.example, consumed by
# mcp_servers.sh / profiles.sh); ~/.claude/.env is a derived copy, not a
# second authored file, so the two cannot drift. Regenerated every run so a
# key added to the project .env always reaches the shell. Kept as its own
# file (rather than sourcing the project .env directly) so the shell still
# works if this repo moves or is deleted.
generate_claude_env() {
    if [[ ! -f "${ENV_FILE}" ]]; then
        print_status "warning" "No ${ENV_FILE} found — skipping \$HOME/.claude/.env generation. Create it first: cp .env.example .env"
        return 0
    fi

    mkdir -p "${CLAUDE_DIR}"

    {
        printf '# Generated by distro_config/setup_env.sh from %s — do not edit by hand.\n' "${ENV_FILE}"
        cat "${ENV_FILE}"
    } > "${CLAUDE_ENV_FILE}"
    chmod 600 "${CLAUDE_ENV_FILE}"

    print_status "success" "Generated \$HOME/.claude/.env from ${ENV_FILE}."
}

# Makes ~/.claude/.env (git-ignored, lives outside every repo's working tree)
# reproducible on a fresh machine: any KEY=value line in it becomes an exported
# shell variable in every new shell, without the value ever touching this repo.
bootstrap_claude_env_sourcing() {
    if grep -qF "${CLAUDE_ENV_MARKER}" "${BASHRC}" 2>/dev/null; then
        print_status "success" "\$HOME/.claude/.env bootstrap already present in \$HOME/.bashrc — skipping."
        return 0
    fi

    {
        printf '\n%s\n' "${CLAUDE_ENV_MARKER}"
        printf 'if [ -f ~/.claude/.env ]; then\n'
        printf '    set -a\n'
        printf '    # shellcheck disable=SC1091\n'
        printf '    source ~/.claude/.env\n'
        printf '    set +a\n'
        printf 'fi\n'
    } >> "${BASHRC}"

    print_status "success" "Added \$HOME/.claude/.env bootstrap to \$HOME/.bashrc."
    print_status "info" "Run 'source ~/.bashrc' (or open a new shell) to pick up its keys now."
}

main() {
    prompt_create_project_env
    generate_claude_env
    bootstrap_claude_env_sourcing
}

main "$@"
